# Generated by Django 4.2.4 on 2023-09-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True),
        ),
    ]
