# Generated by Django 4.2.4 on 2023-09-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0007_remove_comment_comment_comment_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
