# Generated by Django 4.2.4 on 2023-09-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
