# Generated by Django 4.2.4 on 2023-09-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0013_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
