# Generated by Django 4.2.4 on 2023-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0018_alter_comment_id_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_aproved',
            field=models.BooleanField(default=False, verbose_name='Hesap onaylanmış mı?'),
        ),
    ]
