# Generated by Django 4.2.4 on 2023-10-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0019_profile_is_aproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_aproved',
            new_name='is_approved',
        ),
    ]
