# Generated by Django 4.2.4 on 2023-10-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0022_alter_comment_options_alter_likepost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likepost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
