# Generated by Django 4.2.4 on 2023-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0029_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialm.post', verbose_name='Raporlanan Postun Sahibi'),
        ),
    ]
