# Generated by Django 4.2.4 on 2023-10-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0031_ban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ban',
            old_name='reason',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='ban',
            name='duration',
        ),
    ]
