# Generated by Django 4.2.4 on 2023-10-01 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialm', '0032_rename_timestamp_ban_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Banlanma Zamanı'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='description',
            field=models.TextField(verbose_name='Ban sebebi'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Banlanan Kullanıcı'),
        ),
    ]
