# Generated by Django 4.2.4 on 2023-10-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0037_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
