# Generated by Django 4.2.4 on 2023-09-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0004_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
