# Generated by Django 4.2.4 on 2023-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0020_rename_is_aproved_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Moderatör yetkisi verildi mi?'),
        ),
    ]
