# Generated by Django 4.2.4 on 2023-10-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0024_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialm.post'),
        ),
    ]
