# Generated by Django 4.2.4 on 2023-10-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0026_rename_content_report_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='user',
        ),
    ]
