# Generated by Django 4.2.4 on 2023-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0035_profile_birthdate_profile_education_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
