# Generated by Django 4.2.4 on 2023-10-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0038_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
