# Generated by Django 4.2.6 on 2023-10-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0039_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Hesap onaylanmış mı?'),
        ),
    ]
