# Generated by Django 4.2.6 on 2023-10-18 10:53

from django.db import migrations, models
import socialm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0040_alter_profile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=socialm.models.custom_upload_post_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.jpg', upload_to=socialm.models.custom_upload_to),
        ),
    ]
