# Generated by Django 4.2.6 on 2023-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0041_alter_post_image_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notification_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
