# Generated by Django 4.2.6 on 2023-10-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0045_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_notification_check',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
