# Generated by Django 4.2.6 on 2023-10-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialm', '0049_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
